networks:
  custom:
    ipam:
      config:
        - subnet: 10.9.0.0/16
services:
  packerstrivia:
    image: packerstrivia
    build:
      context: .
      dockerfile: PackersTrivia/Dockerfile

  #  mongodb:
  #    image: mongo
  #    environment:
  #      - MONGO_INITDB_ROOT_USERNAME=root
  #      - MONGO_INITDB_ROOT_PASSWORD=mongopw
  #    ports:
  #      - 27017:27017
  #    volumes:
  #      - /var/lib/mongodb/data
  #    networks:
  #      custom:
  #  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=PackersTrivia
      - IncludeErrorDetail=true
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postresql/data
    networks:
      custom:
  
  #  mssql:
  #    container_name: mssql-packers-trivia-db
  #    hostname: mssql-db
  #    image: mcr.microsoft.com/mssql/server:2022-latest
  #    environment:
  #      ACCEPT_EULA: 'Y'
  #      MSSQL_SA_PASSWORD: 'Admin123!'
  #      MSSQL_DATA_DIR: /var/opt/mssql/data
  #      MSSQL_PID: 'Developer'
  #      MSSQL_TCP_PORT: 1433
  #    ports:
  #      - "1433:1433"
  #    volumes:
  #      - mssql_data:/var/lib/mssql/data
  #      - /var/lib/mssql/log
  #      - /var/lib/mssql/secrets
  #    networks:
  #      custom:
  #    healthcheck:
  #      test: [ "CMD-SHELL", "sqlcmd -S localhost -U sa -P Admin123! -Q 'SELECT 1'" ]
  #      interval: 10s
  #      retries: 10
  #      start_period: 40s
  #      timeout: 10s

#  databridge-svc:
#    image: databridge-svc:latest
#    build:
#      context: .
#      dockerfile: DataBridge/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__PostgresConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=DataBridge
#      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=DataBridge;User=sa;Password=Admin123!;TrustServerCertificate=true
#      - ConnectionStrings__MongoConnection=mongodb://root:mongopw@mongodb
#    ports:
#      - 8000:8080
#      - 8001:8080
#    depends_on:
##      - mssql
#      - postgres
#    #      mssql:
#    #        condition: service_healthy
#    networks:
#      custom:
volumes:
  postgres_data:
    driver: local
#  mssql_data:
#    driver: local
